branches:
  only:
  - master
language: scala
scala:
- 2.10.4
- 2.11.7
jdk:
- openjdk7
- oraclejdk8
services:
- cassandra
cache:
  directories:
  - "~/.ivy2"
  apt: true
sbt_args: "-Dsbt.log.noformat=true -sbt-dir ~/.sbt"
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
env:
  global:
  - secure: CYcHLNO0a+E7qV4GIk5CY017c9C4taSBB1phYAM+TxN4XufgBRO5mWRf4JTEnFJeVlJwFEhfVHUdu6nzT4HFXxSaS4OQWLasvrrdAXLF8DIMs3wHPutN7A5SMTRpd8JNmsCAcpFElqa/ya5/CyYA6ooIqGKwDjJr44hbp4RBMeyX4PRhPf2SuHO0lEIc8FMSQrq1e37y2SCYa/vUTWWP9Kxc1sWgxs+7XJosCuedT8HfqsVMFT6FuBx+FbLZ6/Y/hBRZs/KZTss5BcgzaY01VyL7A6HoiWV5U6XdoZF1bzc+KVmSenxiIfpJS9mVLTR+88x/r2qKJLQrnNJ2vs2WoTJGUPyIPe69wOhT01USgfMuf6LQ2UnByR1Ba+H/yR3zEM9lmQ821MSjw45X6d5SOlYzh54d1QO8V18yfMw0IMOam4FaFo0y0xMn0k6QPgYLIBRVspQ8sUdoPf1dJiBpd2KzHwO1g4JAwWRKGrV1xheUKYcJQLEqCaJ+23Q8OlGTiL/NIKokegWgLTZ498UKJezxfwgdNrZEkYaSsu8tMP0xOuummQZc4PIXifVSAbLhV+xuSxGXYGza9ixleX3L+iBHmFr/Q+xpQOq7qwu+KBjjPiuxDUqFyGMqD9Ot4V6QlIDh8ofBL+Bc6T2Lt9mw4DwyOIjxs8cppr5WIN5IEbo=
  - secure: hVKuVbtX2NNBRmv+a2dsUapstOveikuh7myvI7QxIMzYuFVn33XzYIBu8Hkz8VeWnTOX3pLM0Z+Av8RwOTWZ7Z4r4p13XjHCapm3HKt+JLdFnAyIOoPJdQpEix2wSLg0GOOaeid/UQYQjZlg+49X5bzcTb7QmXBL63+Y6sH7CWpiXifj1KVugSxZ2V5zAbMbxI3+y8K+QAuCdroBe7Ygt7D7ndm4ekgYPuytzk2vKIsa5L8ad5lggf433y5YqDw7nKErSJJjzgeD0mRGlif1rEPzNZ4xGWwoUMVSV5gckn40CHOr1vrnPkgP0mwVAf5rGCrAAloTRPfpyyud5tRx32V2c4AyX3FbMZvn8rFPdVQ+mc9YLXyp2v/Qq34YAVWtFvajir6Fhny+Ly/GauNIqUrIn05KLEqkJ6TFbXVZ1EFds/T4clxJlWK1RIWwEj9Yr2A9AqBqTQEZhucGoE25nERPGBuLSgLwAQ/mR7//hlUu9RetlEs7y9JIusy+ufTVmY26WghxNa5gKTz08ImgCG1QjPS9E/o5eufmORKv3HzuF28OyEM04VQ8FyetMoTZz8JiqjyLuJ7ZIrh+eSVhwM1tgojgAlK8/RW0IZe8949x0jCNYwq5xGoWDjVs9eEUaV2/IpOxhXcon9UjCYgP69PlcZDJAOKrDmEAiKEK1so=
  - secure: wPD7MY8kXWn3pRs0Ydh65VrvEY6xnkee4N5Q3/vUsh+wWPC5jeRfwHgcQ6xC/LlxXTrLj5GqLK8HYXNDr+J10J6c5m6SksK592IZg5KltLKWW6JjGBF+rgDsnaTNtiqtEzDnb3+rtdv7a4ihzKMSl+We9ALjj/2W5Bf2Pwqc7t+UnFxBDrubEhdIDpawfsCgANYt0XA3gjb1Dxoern8R4xYwejLeXJr/bf8ukhO3LjNZbbKnBKQPaborKOPil2OHlyDSMHd1RMeqsvHRzI5l7QKlf9WZ2/EbdFHdU44OgdQA89ZOpWhXZv5OxOr0vGsT03BbczZQbXcK1NStf1IRAdEEEBj0TrYwGEDT801k+yPjLcaPQz9L3vjTcVSPAHSCYLAY8H4jaoQP4RKZS3gnPmRBuPpxn93+jo+62gXE6XvXa2EH5jG+PNll2/X7D5/h1sdaNQXB+JAm/1OjCi5zQWTk6svo9j0npG9HLr8uqbDOAts8c1vOU5dKwSTyswh9W3+SjvRpH12DTEy8yEJ5OhLH5IU0N/YJLrivspIPbmd1J8kgltbVoimGwtOWCG3HrQJb0erlhmSopIdFMZGAfzgIX6rMRSY6P46IcAo/H17BGGot9tabT8FAWVp96empc/Z6FAGs44XL+kjmVa1LhlLXiBgJW3//RM3NIH7WBIE=
  - secure: Ld76K8SUj24TbaC3Lh1RQ7ru4rWaXqqKYYNtH4rwLbCLX09rd4pFVcawuIyz8turHfr1Q6UMhKZcwHasxrFfm/FN1x/vc8z2DjlNLnfpHH0kg6g9+ccosY1WZ4Va0Uoratfu1x+FxFBTapUJ+Q1Su2kS29sa6qspMObTMb4dkDx9Gqg+0Ij6ehnL6UTGSY1DKCekNy51iRya000r0rsVt9GPaN258tMDGKJoHKXzkGLVFZfct4xRyzNN2vDHtNAEqWqAYLYxDfFFo0ZImbDb8kxwunf1zV3cwXzmlPh6uC7QebKT6ZJ+TnxWr6eZeNngirt/8fMhL7MuhX+yT0N3aoUykmRvJPrd/eL6yf8wIiktQsjmzxMmi2vfsETii3YcUcVEakOcsFEW6cr8HPKP6zLFdD7B/Ytr3jiUmMG2B1mg9YFBSygIu2MR/7LbC5GQ9ewWSxXcSsWTpDshgnPEWyw5ImVX9PJoEskHA4F1KM+x3RwuOuPh+wvhNPivWtCe5r+knCBd90SIYgIUiK+sLFuLNxSQV6slPh0ZC7fJq9y91zrzE+V584QAAQ3QNfx6N73PJWDCksPS9gC+7Mv92eSPjSE1+X7Rkgr7+gLvWQUW16JbfPy+XkBIs2aB9/TS7GjfzWA4on78bQuYMt0lx1s3Uf51ypHuAyTOpH+WbDk=
